/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pnlDasboard;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.Data;
import model.Sucursal;
import model.Medico;


/**
 *
 * @author Administrador
 */
public class SucursalesMedicos extends javax.swing.JFrame {
    Data dataXYZ = Data.getInstance();
    String nombre;
    Sucursal sucursal;

    
    public SucursalesMedicos(String nombre) {
        initComponents();
        
        this.nombre = nombre;
        labelTitle.setText(nombre + " - Médicos");
        sucursal = dataXYZ.getSucursalByNombre(nombre);
        
        if(sucursal == null){
            showMessage("NO se ha encontrado indormación de esta sucursal.");
        }else{
            showTable(sucursal.getMedicos());
        }
    }

    private SucursalesMedicos() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
    private void showMessage(String msg){
        tableMedicosPanel.setVisible(false);
        msgSucursalMedicoPanel.setVisible(true);
        msgSucursalMedicos.setText(msg);
    }
    
    private void showTable(ArrayList<Medico> lista){
        tableMedicosPanel.setVisible(true);
        msgSucursalMedicoPanel.setVisible(false);
        int cols = 3;
        int rows = lista.size();
        labelTitle.setText(sucursal.getNombre() + " - Médicos (" + rows + ")");
                
        String matriz[][] = new String[rows][cols];
        for(int i = 0; i < rows; i++){
            matriz[i][0] = lista.get(i).getId();
            matriz[i][1] = lista.get(i).getNombre();
            matriz[i][2] = lista.get(i).getEspecialidad();
        }
        
        String[] cabecera = new String[]{"Id", "Nombre", "Especialidad"};
        DefaultTableModel model = new DefaultTableModel(matriz,cabecera);
        tableMedicos.setModel(model);
        
        int[] anchos = new int[]{100, 150, 150};
        for(int i=0; i<cols ;i++){
            tableMedicos.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSButtonMetro2 = new rsbuttom.RSButtonMetro();
        jPanel1 = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        rSButtonMetro5 = new rsbuttom.RSButtonMetro();
        tableMedicosPanel = new javax.swing.JScrollPane();
        tableMedicos = new javax.swing.JTable();
        inputSearch = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rSButtonMetro1 = new rsbuttom.RSButtonMetro();
        msgSucursalMedicoPanel = new javax.swing.JScrollPane();
        msgSucursalMedicos = new javax.swing.JTextArea();

        rSButtonMetro2.setBackground(new java.awt.Color(255, 80, 80));
        rSButtonMetro2.setText("<");
        rSButtonMetro2.setColorHover(new java.awt.Color(255, 90, 90));
        rSButtonMetro2.setColorTextNormal(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(26, 207, 172));
        jPanel1.setPreferredSize(new java.awt.Dimension(857, 513));

        labelTitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelTitle.setForeground(new java.awt.Color(255, 255, 255));
        labelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitle.setText("Nombre Sucursal");

        rSButtonMetro5.setBackground(new java.awt.Color(255, 80, 80));
        rSButtonMetro5.setText("<");
        rSButtonMetro5.setColorHover(new java.awt.Color(255, 90, 90));
        rSButtonMetro5.setColorNormal(new java.awt.Color(255, 80, 80));
        rSButtonMetro5.setColorPressed(new java.awt.Color(255, 90, 90));
        rSButtonMetro5.setColorTextNormal(new java.awt.Color(255, 255, 255));
        rSButtonMetro5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro5ActionPerformed(evt);
            }
        });

        tableMedicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Especialidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableMedicos.setEnabled(false);
        tableMedicos.setRowHeight(30);
        tableMedicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tableMedicosMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMedicosMouseClicked(evt);
            }
        });
        tableMedicosPanel.setViewportView(tableMedicos);

        inputSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSearchActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Búsqueda:");

        rSButtonMetro1.setText("Filtrar");
        rSButtonMetro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro1ActionPerformed(evt);
            }
        });

        msgSucursalMedicoPanel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        msgSucursalMedicoPanel.setHorizontalScrollBar(null);

        msgSucursalMedicos.setEditable(false);
        msgSucursalMedicos.setBackground(new java.awt.Color(26, 207, 172));
        msgSucursalMedicos.setColumns(20);
        msgSucursalMedicos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        msgSucursalMedicos.setRows(2);
        msgSucursalMedicos.setTabSize(10);
        msgSucursalMedicoPanel.setViewportView(msgSucursalMedicos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(rSButtonMetro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(msgSucursalMedicoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rSButtonMetro5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(tableMedicosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(labelTitle)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(rSButtonMetro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(msgSucursalMedicoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rSButtonMetro5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(tableMedicosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(29, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 852, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonMetro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro1ActionPerformed
        String search = inputSearch.getText();
        if("".equals(search)){
            showTable(sucursal.getMedicos());
            return;
        }
        
        ArrayList<Medico> found = sucursal.getMedicosSearch(search);        
        if(found.isEmpty()){
            showMessage("No Se encontraron medicos con lo buscando. \n" 
                    + "Su búsqueda: " + search);
        }else showTable(found);
        inputSearch.setText("");
    }//GEN-LAST:event_rSButtonMetro1ActionPerformed

    private void inputSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSearchActionPerformed

    private void rSButtonMetro5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro5ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_rSButtonMetro5ActionPerformed

    private void tableMedicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMedicosMouseClicked
        /*if(evt.getClickCount() == 2){
            int row = tableMedicos.rowAtPoint(evt.getPoint());
            if (row != -1) {
                String nombre = (String) tableMedicos.getValueAt(row, 0);
                SucursalesEditar sEditar = new SucursalesEditar(nombre);
                sEditar.setVisible(true);
            }
        }*/
    }//GEN-LAST:event_tableMedicosMouseClicked

    private void tableMedicosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMedicosMousePressed
     
    }//GEN-LAST:event_tableMedicosMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SucursalesMedicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SucursalesMedicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SucursalesMedicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SucursalesMedicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SucursalesMedicos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField inputSearch;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JScrollPane msgSucursalMedicoPanel;
    private javax.swing.JTextArea msgSucursalMedicos;
    private rsbuttom.RSButtonMetro rSButtonMetro1;
    private rsbuttom.RSButtonMetro rSButtonMetro2;
    private rsbuttom.RSButtonMetro rSButtonMetro5;
    private javax.swing.JTable tableMedicos;
    private javax.swing.JScrollPane tableMedicosPanel;
    // End of variables declaration//GEN-END:variables

}
